Heading:
  default: "Headline"
  max: 40
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 40 characters"
Blurb:
  default: "Ius vitae ornatus at, ei mea sumo quot dicant. Ei tale democritum eos, in mea timeam accumsan forensibus. Ei his aperiam suavitate. Et debitis convenire sea, viris dictas latine."
  max: 400
  description:
    en: "Enter a short blurb about your community - Max length 400 characters"
Link_sections:
  type: list
  list_type: simple
  default: "Links, "
  description:
    en: "Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered."
Links:
  type: list
  list_type: simple
  default: "Links, Link, #, blank, Hover Text|Links, Link, #, blank, Hover Text|Links, Link, #, blank, Hover Text"
  description:
    en: "Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered."
Social_links:
  type: list
  list_type: simple
  default: "Facebook, Join us on Facebook, #, blank,fab-facebook|Twitter, show some love on Twitter, #, blank,fab-twitter|Youtube, Check out our latest videos on Youtube, #, blank,fab-youtube|Instagram, Check out our latest stuff on Instagram, #, blank,fab-instagram|Linkedin, Check out our latest posts on LinkedIn, #, blank,fab-linkedin"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
Show_footer_on_login_required_page:
  default: true
  description:
    en: "Check this setting if you want the footer to be displayed on the login-required page (only applies if your site is private)"
svg_icons:
  default: "fab-facebook|fab-twitter|fab-youtube|fab-instagram|fab-linkedin"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "
